namespace TrendingGiphyBotWorkerService.Discord.Interactions;

public static class InteractionId
{
    public const string BackButton = "back-button";
    public const string ClearGifSourcesButton = "clear-gif-sources-button";
    public const string ClearGiphyRatingButton = "clear-giphy-rating-button";
    public const string ClearKeywordButton = "clear-keyword-button";
    public const string ClearPostingHoursButton = "clear-posting-hours-button";
    public const string GifSourcesCancelButton = "gif-sources-cancel-button";
    public const string GiphyRatingCancelButton = "giphy-rating-cancel-button";
    public const string GiphyRatingSubmitButton = "giphy-rating-submit-button";
    public const string GifSourcesSubmitButton = "gif-sources-submit-button";
    public const string GifRetentionCancelButton = "gif-retention-cancel-button";
    public const string GifRetentionSubmitButton = "gif-retention-submit-button";
    public const string HowOftenCancelButton = "how-often-cancel-button";
    public const string HowOftenSubmitButton = "how-often-submit-button";
    public const string PostingBehaviorCancelButton = "posting-behavior-cancel-button";
    public const string PostingBehaviorSubmitButton = "posting-behavior-submit-button";
    public const string ResetGiphyRatingButton = "reset-giphy-rating-button";
    public const string ResetHowOftenButton = "reset-how-often-button";
    public const string ResetPostingBehaviorButton = "reset-posting-behavior-button";
    public const string ResetRetentionPeriodButton = "reset-retention-period-button";
    public const string GifSourceKlipyButton = "gif-source-klipy-button";
    public const string GifSourceGiphyButton = "gif-source-giphy-button";
    public const string GiphyRatingAllButton = "giphy-rating-all-button";
    public const string GiphyRatingGButton = "giphy-rating-g-button";
    public const string GiphyRatingPgButton = "giphy-rating-pg-button";
    public const string GiphyRatingPg13Button = "giphy-rating-pg-13-button";
    public const string GiphyRatingRButton = "giphy-rating-r-button";
    public const string GifRetentionOpenButton = "gif-retention-open-button";
    public const string GifSourcesOpenButton = "gif-sources-open-button";
    public const string GiphyRatingOpenButton = "giphy-rating-open-button";
    public const string HowOftenButtonPrefix = "how-often-button";
    public const string HowOftenButtonWildcard = "how-often-button:*";
    public const string HowOftenOpenButton = "how-often-open-button";
    public const string PostingBehaviorOpenButton = "posting-behavior-open-button";
    public const string PostingBehaviorTrendingOnlyButton = "posting-behavior-trending-only-button";
    public const string PostingBehaviorTrendingWithRandomButton = "posting-behavior-trending-with-random-button";
    public const string GifRetentionButtonPrefix = "gif-retention-button";
    public const string GifRetentionButtonWildcard = "gif-retention-button:*";
    public const string ResetRetentionPeriodOpenButton = "reset-retention-period-open-button";
    public const string ConfirmClearButton = "confirm-clear-button";
    public const string CancelClearButton = "cancel-clear-button";
    public const string TrendingGifsWithKeywordButton = "trending-gifs-with-keyword-button";
    public const string TrendingPostingHoursButton = "trending-posting-hours-button";
    public const string TrendingGifsWithKeywordModal = "trending-gifs-with-keyword-modal";
    public const string TrendingGifsWithKeywordTextInput = "trending-gifs-with-keyword-text-input";
    public const string TrendingPostingHoursModal = "trending-posting-hours-modal";
    public const string TrendingPostingHoursFromTextInput = "trending-posting-hours-from-text-input";
    public const string TrendingPostingHoursToTextInput = "trending-posting-hours-to-text-input";
    public const string TrendingPostingHoursUtcOffsetTextInput = "trending-posting-hours-utc-offset-text-input";
}
