# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Debug'

steps:
- script: dotnet build $(Build.SourcesDirectory)/TrendingGiphyBot/TrendingGiphyBot.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(Build.SourcesDirectory)/TrendingGiphyBot/FunctionsTests/FunctionsTests.csproj --no-build --no-restore --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[TrendingGiphyBotModel]*"
  displayName: 'dotnet test $(buildConfiguration)'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'publish test results'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/TrendingGiphyBot/FunctionsTests/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/TrendingGiphyBot/FunctionsTests
  displayName: 'publish coverage results'