//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendingGiphyBot.Dals
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobConfig
    {
        public decimal ChannelId { get; set; }
        public int Interval { get; set; }
        public string Time { get; set; }
        public bool RandomIsOn { get; set; }
        public string RandomSearchString { get; set; }
        public Nullable<short> MinQuietHour { get; set; }
        public Nullable<short> MaxQuietHour { get; set; }
    
        public virtual TimeRecord Time1 { get; set; }
    }
}
