//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendingGiphyBot.Dals
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlHistory
    {
        public decimal ChannelId { get; set; }
        public string Url { get; set; }
        public System.DateTime Stamp { get; set; }
    }
}
