// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendingGiphyBotWorkerService.Database;

#nullable disable

namespace TrendingGiphyBotWorkerService.Migrations;

[DbContext(typeof(TrendingGiphyBotDbContext))]
partial class TrendingGiphyBotDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Property<ulong>("ChannelId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Frequency")
                    .HasColumnType("INTEGER");

                b.Property<string>("GifKeyword")
                    .HasColumnType("TEXT");

                b.Property<int>("GifPostingBehaviorId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("GifSource")
                    .HasColumnType("INTEGER");

                b.Property<string>("GiphyRating")
                    .HasColumnType("TEXT");

                b.Property<int>("IntervalId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("PostingHoursFrom")
                    .HasColumnType("INTEGER");

                b.Property<int?>("PostingHoursTo")
                    .HasColumnType("INTEGER");

                b.Property<string>("UtcOffset")
                    .HasColumnType("TEXT");

                b.HasKey("ChannelId");

                b.HasIndex("GifPostingBehaviorId");

                b.HasIndex("IntervalId");

                b.ToTable("ChannelSettings", (string)null);
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GiphyPost", b =>
            {
                b.Property<long>("GiphyPostId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<string>("GiphyDataId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("GiphyPostId");

                b.HasIndex("ChannelId");

                b.ToTable("GiphyPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.KlipyPost", b =>
            {
                b.Property<long>("KlipyPostId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<ulong>("KlipyDataId")
                    .HasColumnType("INTEGER");

                b.HasKey("KlipyPostId");

                b.HasIndex("ChannelId");

                b.ToTable("KlipyPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", b =>
            {
                b.Property<int>("GifPostingBehaviorId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("GifPostingBehaviorId");

                b.ToTable("GifPostingBehaviors");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.Intervals.Interval", b =>
            {
                b.Property<int>("IntervalId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("IntervalId");

                b.ToTable("Intervals");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", "GifPostingBehavior")
                    .WithMany("ChannelSettings")
                    .HasForeignKey("GifPostingBehaviorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TrendingGiphyBotWorkerService.Intervals.Interval", "Interval")
                    .WithMany("ChannelSettings")
                    .HasForeignKey("IntervalId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("GifPostingBehavior");

                b.Navigation("Interval");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GiphyPost", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", "ChannelSettings")
                    .WithMany("GiphyPosts")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.KlipyPost", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", "ChannelSettings")
                    .WithMany("KlipyPosts")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Navigation("GiphyPosts");

                b.Navigation("KlipyPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", b =>
            {
                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.Intervals.Interval", b =>
            {
                b.Navigation("ChannelSettings");
            });
#pragma warning restore 612, 618
    }
}
