// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendingGiphyBotModel;

namespace TrendingGiphyBotModel.Migrations
{
    [DbContext(typeof(TrendingGiphyBotContext))]
    partial class TrendingGiphyBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrendingGiphyBotModel.JobConfig", b =>
                {
                    b.Property<decimal>("ChannelId");

                    b.Property<int?>("Interval");

                    b.Property<int?>("IntervalMinutes");

                    b.Property<short?>("MaxQuietHour");

                    b.Property<short?>("MinQuietHour");

                    b.Property<string>("Prefix");

                    b.Property<string>("RandomSearchString");

                    b.Property<string>("Time");

                    b.HasKey("ChannelId");

                    b.ToTable("JobConfig");
                });

            modelBuilder.Entity("TrendingGiphyBotModel.UrlCache", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Stamp");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("UrlCache");
                });

            modelBuilder.Entity("TrendingGiphyBotModel.UrlHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ChannelId");

                    b.Property<DateTime>("Stamp");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("UrlHistory");
                });

            modelBuilder.Entity("TrendingGiphyBotModel.UrlHistory", b =>
                {
                    b.HasOne("TrendingGiphyBotModel.JobConfig", "JobConfig")
                        .WithMany("UrlHistories")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
