// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendingGiphyBotWorkerService.Database;

#nullable disable

namespace TrendingGiphyBotWorkerService.Migrations;

[DbContext(typeof(TrendingGiphyBotDbContext))]
[Migration("20260217043344_RefactorPostingHoursToValueObject")]
partial class RefactorPostingHoursToValueObject
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Property<ulong>("ChannelId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Frequency")
                    .HasColumnType("INTEGER");

                b.Property<string>("GifKeyword")
                    .HasColumnType("TEXT");

                b.Property<int>("GifPostingBehavior")
                    .HasColumnType("INTEGER");

                b.Property<int>("GifSource")
                    .HasColumnType("INTEGER");

                b.Property<string>("GiphyRating")
                    .HasColumnType("TEXT");

                b.Property<int>("Interval")
                    .HasColumnType("INTEGER");

                b.Property<int?>("RetentionDays")
                    .HasColumnType("INTEGER");

                b.Property<string>("UtcOffset")
                    .HasColumnType("TEXT");

                b.HasKey("ChannelId");

                b.ToTable("ChannelSettings", (string)null);
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GiphyPost", b =>
            {
                b.Property<long>("GiphyPostId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("GiphyDataId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("GiphyPostId");

                b.HasIndex("CreatedUtc")
                    .HasDatabaseName("IX_GiphyPosts_CreatedUtc");

                b.HasIndex("ChannelId", "CreatedUtc")
                    .IsDescending(false, true)
                    .HasDatabaseName("IX_GiphyPosts_ChannelId_CreatedUtc");

                b.ToTable("GiphyPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.KlipyPost", b =>
            {
                b.Property<long>("KlipyPostId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT");

                b.Property<ulong>("KlipyDataId")
                    .HasColumnType("INTEGER");

                b.HasKey("KlipyPostId");

                b.HasIndex("CreatedUtc")
                    .HasDatabaseName("IX_KlipyPosts_CreatedUtc");

                b.HasIndex("ChannelId", "CreatedUtc")
                    .IsDescending(false, true)
                    .HasDatabaseName("IX_KlipyPosts_ChannelId_CreatedUtc");

                b.ToTable("KlipyPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.OwnsOne("TrendingGiphyBotWorkerService.ChannelSettings.PostingHours", "PostingHours", b1 =>
                    {
                        b1.Property<ulong>("ChannelSettingsModelChannelId")
                            .HasColumnType("INTEGER");

                        b1.Property<int?>("From")
                            .HasColumnType("INTEGER")
                            .HasColumnName("PostingHoursFrom");

                        b1.Property<int?>("To")
                            .HasColumnType("INTEGER")
                            .HasColumnName("PostingHoursTo");

                        b1.HasKey("ChannelSettingsModelChannelId");

                        b1.ToTable("ChannelSettings");

                        b1.WithOwner()
                            .HasForeignKey("ChannelSettingsModelChannelId");
                    });

                b.Navigation("PostingHours");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GiphyPost", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", "ChannelSettings")
                    .WithMany("GiphyPosts")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.KlipyPost", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", "ChannelSettings")
                    .WithMany("KlipyPosts")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Navigation("GiphyPosts");

                b.Navigation("KlipyPosts");
            });
#pragma warning restore 612, 618
    }
}
