// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrendingGiphyBotWorkerService.Database;

#nullable disable

namespace TrendingGiphyBotWorkerService.Migrations;

[DbContext(typeof(TrendingGiphyBotDbContext))]
[Migration("20260122045954_GifPostingBehavior")]
partial class GifPostingBehavior
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Property<ulong>("ChannelId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Frequency")
                    .HasColumnType("INTEGER");

                b.Property<string>("GifKeyword")
                    .HasColumnType("TEXT");

                b.Property<int>("GifPostingBehaviorId")
                    .HasColumnType("INTEGER");

                b.Property<int>("IntervalId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PostingHoursFrom")
                    .HasColumnType("TEXT");

                b.Property<string>("PostingHoursTo")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("UtcOffset")
                    .HasColumnType("TEXT");

                b.HasKey("ChannelId");

                b.HasIndex("GifPostingBehaviorId");

                b.HasIndex("IntervalId");

                b.ToTable("ChannelSettings", (string)null);
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GifPost", b =>
            {
                b.Property<long>("GifPostId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<ulong>("ChannelId")
                    .HasColumnType("INTEGER");

                b.Property<string>("GiphyDataId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("GifPostId");

                b.HasIndex("ChannelId");

                b.ToTable("GifPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", b =>
            {
                b.Property<int>("GifPostingBehaviorId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("GifPostingBehaviorId");

                b.ToTable("GifPostingBehaviors");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.Intervals.Interval", b =>
            {
                b.Property<int>("IntervalId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("IntervalId");

                b.ToTable("Intervals");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", "GifPostingBehavior")
                    .WithMany("ChannelSettings")
                    .HasForeignKey("GifPostingBehaviorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TrendingGiphyBotWorkerService.Intervals.Interval", "Interval")
                    .WithMany("ChannelSettings")
                    .HasForeignKey("IntervalId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("GifPostingBehavior");

                b.Navigation("Interval");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.GifPost", b =>
            {
                b.HasOne("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", "ChannelSettings")
                    .WithMany("GifPosts")
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.ChannelSettings.ChannelSettingsModel", b =>
            {
                b.Navigation("GifPosts");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.GifPostingBehavior.GifPostingBehaviorModel", b =>
            {
                b.Navigation("ChannelSettings");
            });

        modelBuilder.Entity("TrendingGiphyBotWorkerService.Intervals.Interval", b =>
            {
                b.Navigation("ChannelSettings");
            });
#pragma warning restore 612, 618
    }
}
